name = "llmgateway-api"
main = "dist/worker.js"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

[env.production]
workers_dev = false
routes = [{ pattern = "llm.leeapp.dev/*", zone_name = "leeapp.dev" }]

[env.staging]
workers_dev = true

# D1 Database bindings
[[env.production.d1_databases]]
binding = "DB"
database_name = "llmgateway-prod"
database_id = "your-production-d1-database-id"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "llmgateway-staging"
database_id = "your-staging-d1-database-id"

# Environment variables
[env.production.vars]
NODE_ENV = "production"
STRIPE_SECRET_KEY = ""
STRIPE_WEBHOOK_SECRET = ""
POSTHOG_API_KEY = ""
BETTER_AUTH_SECRET = ""

[env.staging.vars]
NODE_ENV = "staging"
STRIPE_SECRET_KEY = ""
STRIPE_WEBHOOK_SECRET = ""
POSTHOG_API_KEY = ""
BETTER_AUTH_SECRET = ""

[build]
command = "pnpm build"
cwd = "."
watch_dir = "src"

